name: pre-release

on:
  push:
    branches:
      - dev
jobs:
  pre-release:
    name: Pre-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: read
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Node.js 16.x
        uses: actions/setup-node@master
        with:
          node-version: 16.x

      - name: Create .npmrc
        run: echo ${JFROG_NPMRC_B64} | base64 -d >> .npmrc
        env:
          JFROG_NPMRC_B64: ${{ secrets.JFROG_NPMRC_B64 }}

      - name: Install Dependencies
        run: npm ci

      - name: Check if there are changes
        run: npm exec -- changeset status --since=dev

      - name: Install zx
        run: npm install -g zx

      - name: Remove .npmrc
        run: rm -rf .npmrc
      
      - name: Create prerelease
        run: npm run release
      - uses: EndBug/add-and-commit@v7 # You can change this to use a specific version.
        with:
          add: ['package.json', 'package-lock.json']


      # - name: Create Release Pull Request or Publish to npm
      #   id: changesets
      #   uses: changesets/action@master
      #   with:
      #     version: npm run version:pre
      #     # This expects you to have a script called release which does a build for your packages and calls changeset publish
      #     publish: npm run publish:pre
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     JFROG_NPMRC_B64: ${{ secrets.JFROG_NPMRC_B64 }}


      # - name: Send a Slack notification if a publish happens
      #   if: steps.changesets.outputs.published == 'true'
      #   # You can do something when a publish happens.
      #   run: my-slack-bot send-notification --message "A new version of ${GITHUB_REPOSITORY} was published!"

